// +build ignore

// This program generates contributors.go. It can be invoked by running
// go generate
package main

import (
	"github.com/trustwallet/blockatlas/coin"
	"os"
	"text/template"
	"time"
)

func main() {
	coins, err := coin.Load("coins.yml")
	if err != nil {
		panic(err)
	}

	f, err := os.Create("list.go")
	if err != nil {
		panic(err)
	}
	defer f.Close()

	err = slip44Template.Execute(f, map[string]interface{}{
		"Timestamp": time.Now(),
		"Coins": coins,
	})
	if err != nil {
		panic(err)
	}
}

var slip44Template = template.Must(template.New("").Parse(
`// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at
// {{ .Timestamp }}
// using data from coins.yml
package coin

const (
{{- range .Coins }}
	{{ .Symbol }} = "{{ .Handle }}"
{{- end }}
)

var Coins = map[string]Coin{
{{- range .Coins }}
	"{{ .Handle }}": {
		ID: {{ .ID }},
		Handle: "{{ .Handle }}",
		Symbol: "{{ .Symbol }}",
		Title: "{{ .Title }}",
		Decimals: {{ .Decimals }},
		{{- if .BlockTime }}
		BlockTime: {{ .BlockTime }},
		{{- end }}
		{{- if .SampleAddr }}
		SampleAddr: "{{ .SampleAddr }}",
		{{- end }}
		{{- if .SampleToken }}
		SampleToken: "{{ .SampleToken }}",
		{{- end }}
	},
{{- end }}
}
`))
