// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at
// 2019-07-07 13:44:51.351206 +0200 CEST m=+0.002852760
// using data from coins.yml
package coin

const (
	ETH = "ethereum"
	ETC = "classic"
	ICX = "icon"
	ATOM = "cosmos"
	XRP = "ripple"
	XLM = "stellar"
	POA = "poa"
	TRX = "tron"
	NIM = "nimiq"
	IOTX = "iotex"
	ZIL = "zilliqa"
	AION = "aion"
	THETA = "theta"
	BNB = "binance"
	VET = "vechain"
	CLO = "callisto"
	TOMO = "tomochain"
	TT = "thundertoken"
	ONT = "ontology"
	XTZ = "tezos"
	KIN = "kin"
	GO = "gochain"
	WAN = "wanchain"
	WAVES = "waves"
	SEM = "semux"
)

var Coins = map[string]Coin{
	"ethereum": {
		ID: 60,
		Handle: "ethereum",
		Symbol: "ETH",
		Title: "Ether",
		Decimals: 18,
		SampleAddr: "0xfc10cab6a50a1ab10c56983c80cc82afc6559cf1",
	},
	"classic": {
		ID: 61,
		Handle: "classic",
		Symbol: "ETC",
		Title: "Ether Classic",
		Decimals: 18,
		SampleAddr: "0xf3524415b6D873205B4c3Cda783527b2aC4daAA9",
	},
	"icon": {
		ID: 74,
		Handle: "icon",
		Symbol: "ICX",
		Title: "ICON",
		Decimals: 18,
		SampleAddr: "hxee691e7bccc4eb11fee922896e9f51490e62b12e",
	},
	"cosmos": {
		ID: 118,
		Handle: "cosmos",
		Symbol: "ATOM",
		Title: "Cosmos ATOM",
		Decimals: 6,
		SampleAddr: "cosmos1rw62phusuv9vzraezr55k0vsqssvz6ed52zyrl",
	},
	"ripple": {
		ID: 144,
		Handle: "ripple",
		Symbol: "XRP",
		Title: "Ripple",
		Decimals: 6,
		SampleAddr: "rMQ98K56yXJbDGv49ZSmW51sLn94Xe1mu1",
	},
	"stellar": {
		ID: 148,
		Handle: "stellar",
		Symbol: "XLM",
		Title: "Stellar Lumens",
		Decimals: 7,
		SampleAddr: "GDKIJJIKXLOM2NRMPNQZUUYK24ZPVFC6426GZAEP3KUK6KEJLACCWNMX",
	},
	"poa": {
		ID: 178,
		Handle: "poa",
		Symbol: "POA",
		Title: "Poa",
		Decimals: 18,
		SampleAddr: "0x1fddEc96688e0538A316C64dcFd211c491ECf0d8",
	},
	"tron": {
		ID: 195,
		Handle: "tron",
		Symbol: "TRX",
		Title: "Tron",
		Decimals: 6,
		SampleAddr: "TMuA6YqfCeX8EhbfYEg5y7S4DqzSJireY9",
	},
	"nimiq": {
		ID: 242,
		Handle: "nimiq",
		Symbol: "NIM",
		Title: "Nimiq",
		Decimals: 5,
		BlockTime: 60000,
		SampleAddr: "NQ86 2H8F YGU5 RM77 QSN9 LYLH C56A CYYR 0MLA",
	},
	"iotex": {
		ID: 304,
		Handle: "iotex",
		Symbol: "IOTX",
		Title: "IoTeX",
		Decimals: 0,
		SampleAddr: "io1mwekae7qqwlr23220k5n9z3fmjxz72tuchra3m",
	},
	"zilliqa": {
		ID: 313,
		Handle: "zilliqa",
		Symbol: "ZIL",
		Title: "Zilliqa",
		Decimals: 0,
		SampleAddr: "0x88aF5BA10796D9091D6893eED4db23ef0bbbCa37",
	},
	"aion": {
		ID: 425,
		Handle: "aion",
		Symbol: "AION",
		Title: "Aion",
		Decimals: 18,
		SampleAddr: "0xa07981da70ce919e1db5f051c3c386eb526e6ce8b9e2bfd56e3f3d754b0a17f3",
	},
	"theta": {
		ID: 500,
		Handle: "theta",
		Symbol: "THETA",
		Title: "Theta",
		Decimals: 0,
		SampleAddr: "0xac0eeb6ee3e32e2c74e14ac74155063e4f4f981f",
	},
	"binance": {
		ID: 714,
		Handle: "binance",
		Symbol: "BNB",
		Title: "Binance",
		Decimals: 18,
		BlockTime: 1000,
		SampleAddr: "tbnb1fhr04azuhcj0dulm7ka40y0cqjlafwae9k9gk2",
	},
	"vechain": {
		ID: 818,
		Handle: "vechain",
		Symbol: "VET",
		Title: "VeChain Token",
		Decimals: 0,
		SampleAddr: "0xB5e883349e68aB59307d1604555AC890fAC47128",
	},
	"callisto": {
		ID: 820,
		Handle: "callisto",
		Symbol: "CLO",
		Title: "Callisto",
		Decimals: 18,
		SampleAddr: "0x39ec1c88a7a7c1a575e8c8f42eff7630d9278179",
	},
	"tomochain": {
		ID: 889,
		Handle: "tomochain",
		Symbol: "TOMO",
		Title: "TOMO",
		Decimals: 0,
		SampleAddr: "0x7daa83030e3086477b79b6e757ca8608899fe783",
	},
	"thundertoken": {
		ID: 1001,
		Handle: "thundertoken",
		Symbol: "TT",
		Title: "ThunderCore",
		Decimals: 18,
		SampleAddr: "0x0ad80a408eac4f17ba0a9de8a12d8736f60700c3",
	},
	"ontology": {
		ID: 1024,
		Handle: "ontology",
		Symbol: "ONT",
		Title: "Ontology",
		Decimals: 0,
		SampleAddr: "AUyL4TZ1zFEcSKDJrjFnD7vsq5iFZMZqT7",
	},
	"tezos": {
		ID: 1729,
		Handle: "tezos",
		Symbol: "XTZ",
		Title: "Tezos",
		Decimals: 6,
		SampleAddr: "tz1WCd2jm4uSt4vntk4vSuUWoZQGhLcDuR9q",
	},
	"kin": {
		ID: 2017,
		Handle: "kin",
		Symbol: "KIN",
		Title: "Kin",
		Decimals: 5,
		SampleAddr: "GBHKUZ7C2SZ5N3X2S7O6TT6LNUWSEA2BXMSR5GTTSR6VZARSVAXIQNGH",
	},
	"gochain": {
		ID: 6060,
		Handle: "gochain",
		Symbol: "GO",
		Title: "GoChain GO",
		Decimals: 18,
		SampleAddr: "0x76c2F81716A8D198a00502Ae9a59126418899FDe",
	},
	"wanchain": {
		ID: 5718350,
		Handle: "wanchain",
		Symbol: "WAN",
		Title: "Wanchain",
		Decimals: 18,
		SampleAddr: "0x36cEdc3A9d969306AF4F7CA2b83ABBf74095914d",
	},
	"waves": {
		ID: 5741564,
		Handle: "waves",
		Symbol: "WAVES",
		Title: "WAVES",
		Decimals: 8,
		SampleAddr: "3P7wz6TXienpw3BHe8eHUEuZWb6WE58kgnQ",
	},
	"semux": {
		ID: 7562605,
		Handle: "semux",
		Symbol: "SEM",
		Title: "Semux",
		Decimals: 9,
		SampleAddr: "0x8197987c401a3466ad678b2080b24838ebd95b41",
	},
}
